name: build
on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-checkov:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: update release
        run: |
          # update checkov version
          version=$(curl -s https://api.github.com/repos/bridgecrewio/checkov/releases/latest | jq -r '.name')
          sed -i'.bkp' -e 's/docker:\/\/bridgecrew\/checkov.*'\''\/docker:\/\/bridgecrew\/checkov:'"${version}"'\''/g' action.yml
          rm action.yml.bkp
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: Bump checkov container version
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@31c05bec812d1a339edacdf9fbf5b068691a65b2 # 1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
